version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: alura-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: aluradb
      MYSQL_USER: alura
      MYSQL_PASSWORD: testedb
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - default

  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "8088:8080"
    depends_on:
      - mysql
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    networks:
      - default

  appalura:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://mysql:3306/aluradb
    depends_on:
      - mysql
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  mysql_data: