version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: alura-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: aluradb
      MYSQL_USER: alura
      MYSQL_PASSWORD: testedb
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "8088:8080"
    depends_on:
      - mysql
    environment:
      ADMINER_DEFAULT_SERVER: mysql

volumes:
  mysql_data: