server:
  port: 8080
  servlet:
    contextPath: /api
  error:
    includeStacktrace: ALWAYS

springdoc:
  api-docs:
    path: /api-docs
  packages-to-scan: br.com.alura
  swagger-ui:
    path: /swagger-ui

spring:
  application:
    name: test-case-java
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3307/aluradb}
    username: ${DB_USERNAME:alura}
    password: ${DB_PASSWORD:testedb}
    driverClassName: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migrations

  jpa:
    hibernate:
      ddl-auto: "none"
      naming.physical-strategy: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
    properties:
      hibernate:
        query.fail_on_pagination_over_collection_fetch: true
        hql.bulk_id_strategy: "org.hibernate.hql.spi.id.inline.InlineIdsInClauseBulkIdStrategy"
    open-in-view: false
