server:
  port: 8080
  servlet:
    contextPath: /api
  error:
    includeStacktrace: ALWAYS

spring:
  application:
    name: test-case-java
  datasource:
    url: jdbc:mysql://localhost:3307/aluradb
    username: alura
    password: testedb
    driverClassName: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migrations

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
