server:
  port: 8080
  servlet:
    contextPath: /api
  error:
    includeStacktrace: ALWAYS

springdoc:
  api-docs:
    path: /api-docs
  packages-to-scan: br.com.alura
  swagger-ui:
    path: /swagger-ui

spring:
  application:
    name: test-case-java
  datasource:
    url: jdbc:mysql://localhost:3307/aluradb
    username: alura
    password: testedb
    driverClassName: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migrations

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
